export interface industry {
    industry_name: string;
    industry_code: string;
}

export const industries: industry[] = [
    { industry_name: "Advertising", industry_code: "AD" },
    { industry_name: "Aerospace", industry_code: "AE" },
    { industry_name: "Agribusiness", industry_code: "AB" },
    { industry_name: "Agriculture", industry_code: "AG" },
    { industry_name: "Architecture", industry_code: "AR" },
    { industry_name: "Art", industry_code: "AR" },
    { industry_name: "Automotive", industry_code: "AU" },
    { industry_name: "Aviation", industry_code: "AV" },
    { industry_name: "Banking", industry_code: "BA" },
    { industry_name: "Biotechnology", industry_code: "BI" },
    { industry_name: "Chemical", industry_code: "CH" },
    { industry_name: "Construction", industry_code: "CO" },
    { industry_name: "Consulting", industry_code: "CS" },
    { industry_name: "Customer Service", industry_code: "CS" },
    { industry_name: "Defense", industry_code: "DF" },
    { industry_name: "Design", industry_code: "DS" },
    { industry_name: "E-commerce", industry_code: "EC" },
    { industry_name: "Education", industry_code: "ED" },
    { industry_name: "Electronics", industry_code: "EL" },
    { industry_name: "Energy", industry_code: "EN" },
    { industry_name: "Entertainment", industry_code: "ET" },
    { industry_name: "Environmental Services", industry_code: "ES" },
    { industry_name: "Event Management", industry_code: "EM" },
    { industry_name: "Fashion", industry_code: "FA" },
    { industry_name: "Finance", industry_code: "FI" },
    { industry_name: "Fitness & Wellness", industry_code: "FW" },
    { industry_name: "Food & Beverage", industry_code: "FB" },
    { industry_name: "Government", industry_code: "GV" },
    { industry_name: "Healthcare", industry_code: "HC" },
    { industry_name: "Hospitality", industry_code: "HO" },
    { industry_name: "Human Resources", industry_code: "HR" },
    { industry_name: "Information Technology", industry_code: "IT" },
    { industry_name: "Insurance", industry_code: "IN" },
    { industry_name: "Legal", industry_code: "LG" },
    { industry_name: "Logistics", industry_code: "LG" },
    { industry_name: "Manufacturing", industry_code: "MA" },
    { industry_name: "Marine", industry_code: "MR" },
    { industry_name: "Market Research", industry_code: "MR" },
    { industry_name: "Marketing", industry_code: "MK" },
    { industry_name: "Media", industry_code: "ME" },
    { industry_name: "Mining", industry_code: "MI" },
    { industry_name: "Music", industry_code: "MU" },
    { industry_name: "Non-Profit", industry_code: "NP" },
    { industry_name: "Petroleum", industry_code: "PE" },
    { industry_name: "Pharmaceuticals", industry_code: "PH" },
    { industry_name: "Photography", industry_code: "PH" },
    { industry_name: "Public Relations", industry_code: "PR" },
    { industry_name: "Publishing", industry_code: "PU" },
    { industry_name: "Real Estate", industry_code: "RE" },
    { industry_name: "Research & Development", industry_code: "RD" },
    { industry_name: "Retail", industry_code: "RT" },
    { industry_name: "SEO Services", industry_code: "SS" },
    { industry_name: "Security", industry_code: "SE" },
    { industry_name: "Social Media", industry_code: "SM" },
    { industry_name: "Sports", industry_code: "SP" },
    { industry_name: "Supply Chain Management", industry_code: "SC" },
    { industry_name: "Technology", industry_code: "TE" },
    { industry_name: "Telecommunications", industry_code: "TC" },
    { industry_name: "Textiles", industry_code: "TX" },
    { industry_name: "Translation & Localization", industry_code: "TL" },
    { industry_name: "Transportation", industry_code: "TR" },
    { industry_name: "Travel & Tourism", industry_code: "TT" },
    { industry_name: "Utilities", industry_code: "UT" },
    { industry_name: "Wholesale", industry_code: "WH" },
    { industry_name: "Writing & Editing", industry_code: "WE" },
    { industry_name: "Others", industry_code: "OT" },

];

